version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_app_1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - certbot-etc:/etc/letsencrypt       # Persist certs
      - certbot-var:/var/lib/letsencrypt   # Persist cert logs/data
    depends_on:
      - db
    networks:
      - portfolio

  db:
    image: mysql:8.0
    container_name: portfolio_db_1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: portfolio
      MYSQL_USER: ozaswei
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - portfolio

volumes:
  db_data:
  certbot-etc:
  certbot-var:

networks:
  portfolio:
